### ISSUE TITLE
Self-closing tags do not closes

### ISSUE THREAD

**Issue by pythonpioneer** [pythonpioneer/html-to-jsx#3]
The self-closing tags do not close after converting into JSX if we pass any self-closing tags that have been closed in input.

we can reproduce the bug with:

```{r}
Input: 
       <input class="demo" for="demo">
       <input class="demo" for="demo">
       <input class="demo" for="demo">
       <input className="demo" htmlFor="demo"/>

Output: 
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo"/>

Expected Output: 
       <input className="demo" htmlFor="demo"/>
       <input className="demo" htmlFor="demo"/>
       <input className="demo" htmlFor="demo"/>
       <input className="demo" htmlFor="demo"/>

        
```

**Comment by planetarybeing** [comment]
Here's the updated code
      
       <input class="demo" for="demo">
       <input class="demo" for="demo">
       <input class="demo" for="demo">
       <input className="demo" htmlFor="demo" />

Output: 
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo">
       <input className="demo" htmlFor="demo" />

Expected Output: 
       <input className="demo" htmlFor="demo" />
       <input className="demo" htmlFor="demo" />
       <input className="demo" htmlFor="demo" />
       <input className="demo" htmlFor="demo" />

Self closing tags need a trailing slash ' / ' - closing tag is optional for self closing tags

**Comment by pythonpioneer** [comment]
@planetarybeing Thanks for your feedback, I really appreciate it.
